#![allow(
    clippy::indexing_slicing,
    reason = "bounded generated byte fixtures deliberately mutate and truncate exact offsets"
)]
use super::*;
use crate::search_checkpoint::{Journal, tests::Scratch};

fn policy() -> AdmissionPolicyV1 {
    crate::boolean_search_record::tests::generated_policy_with_ceilings([1_000_000; 4])
}
fn legacy(scope: u8) -> Result<Vec<u8>, String> {
    let mut raw = b"BRISSD01".to_vec();
    for text in ["NSE-NIFTY", "zerodha"] {
        raw.extend_from_slice(&u64::try_from(text.len()).map_err(display)?.to_le_bytes());
        raw.extend_from_slice(text.as_bytes());
    }
    raw.push(scope);
    for day in [1_i64, 20, 21, 40] {
        raw.extend_from_slice(&day.to_le_bytes());
    }
    raw.extend_from_slice(&Cursor::new(&[0, 30]).map_err(debug)?.encode());
    raw.extend_from_slice(&policy().digest());
    raw.extend_from_slice(&runner::signal_candle_stop::Policy::V1.digest());
    raw.extend_from_slice(&crate::index_consistency::INDEX_STOP.digest());
    for word in [
        2_u64, 100, 2, 1000, 1_000_000, 255, 0, 2, 4, 1000, 1000, 1_000_000, 1_000_000, 1_000_000,
        1000,
    ] {
        raw.extend_from_slice(&word.to_le_bytes());
    }
    for rung in 0..8 {
        if scope & (1 << rung) != 0 {
            raw.extend_from_slice(&[1 + rung; 32]);
            raw.extend_from_slice(&[11 + rung; 32]);
        }
    }
    Ok(raw)
}
fn current(scope: u8) -> Result<Vec<u8>, String> {
    let inner = legacy(scope)?;
    let mut raw = b"BRISSD02".to_vec();
    raw.extend_from_slice(&u64::try_from(inner.len()).map_err(display)?.to_le_bytes());
    raw.extend_from_slice(&inner);
    raw.extend_from_slice(&policy().canonical_bytes());
    for rung in 0..8 {
        if scope & (1 << rung) != 0 {
            for marker in [21 + rung, 31 + rung, 41 + rung, 51 + rung] {
                raw.extend_from_slice(&[marker; 32]);
            }
        }
    }
    Ok(raw)
}
fn budget() -> Budget {
    Budget {
        bytes: 10_000_000,
        records: 100,
        grammar_nodes: 10_000,
        bootstrap_work: 10_000,
        split_work: 10_000,
    }
}

#[test]
fn declaration_versions_keep_exact_scope_sources_and_preallocation_policy() -> Result<(), String> {
    for scope in [1, 128, 129, 255] {
        let old = legacy(scope)?;
        let old = Declaration::decode(&old)?;
        assert_eq!(old.version(), 1);
        assert!(old.policy().is_none());
        assert!(old.source_context(0, false).is_none());
        let bytes = current(scope)?;
        let parsed = Declaration::decode(&bytes)?;
        assert_eq!(parsed.version(), 2);
        assert_eq!(parsed.identity(), hash(&bytes));
        assert_eq!(parsed.index(), "NSE-NIFTY");
        assert_eq!(parsed.feed(), "zerodha");
        assert_eq!(parsed.scope(), scope);
        assert_eq!(parsed.training_days(), (1, 20));
        assert_eq!(parsed.later_days(), (21, 40));
        assert_eq!(parsed.policy(), Some(policy()));
        for rung in 0..8 {
            assert_eq!(
                parsed.source(rung, false).is_some(),
                scope & (1 << rung) != 0
            );
            assert_eq!(
                parsed.source_context(rung, true).is_some(),
                scope & (1 << rung) != 0
            );
            if let Some(source) = parsed.source(rung, true) {
                assert_eq!((source.first_day, source.last_day), (21, 40));
            }
        }
        assert!(parsed.source(8, false).is_none());
    }
    Ok(())
}

#[test]
fn truncation_trailing_unknown_policy_unpinned_context_and_nested_envelopes_refuse()
-> Result<(), String> {
    let bytes = current(129)?;
    for end in 0..bytes.len() {
        assert!(
            Declaration::decode(&bytes[..end]).is_err(),
            "accepted truncated extent {end}"
        );
    }
    let mut altered = bytes.clone();
    altered.push(0);
    assert!(Declaration::decode(&altered).is_err());
    let mut altered = bytes.clone();
    altered[7] = b'3';
    assert!(Declaration::decode(&altered).is_err());
    let mut altered = bytes.clone();
    altered[16 + 7] = b'2';
    assert!(Declaration::decode(&altered).is_err());
    let mut altered = bytes.clone();
    altered[8..16].copy_from_slice(&u64::MAX.to_le_bytes());
    assert!(Declaration::decode(&altered).is_err());
    let mut altered = bytes;
    let len = altered.len();
    altered[len - 32..].fill(0);
    assert!(Declaration::decode(&altered).is_err());
    let mut altered = current(1)?;
    let at = 16 + legacy(1)?.len();
    altered[at..at + runner::admission::ADMISSION_POLICY_CANONICAL_LEN_V1].copy_from_slice(
        &policy()
            .with_search_probability_ceiling(100)
            .canonical_bytes(),
    );
    assert!(Declaration::decode(&altered).is_err());
    assert!(Declaration::decode(&legacy(0)?).is_err());
    Ok(())
}

#[test]
fn pinned_prefix_survives_new_pending_checkpoint_without_relabelling_or_future_reads()
-> Result<(), String> {
    let scratch = Scratch::new().map_err(display)?;
    let bytes = current(1)?;
    let identity = hash(&bytes);
    let cursor = Cursor::new(&[0, 30]).map_err(debug)?;
    let mut journal = Journal::open(&scratch.0, NAMESPACE, identity)?;
    let mut initial = checkpoint::Frame::declaration(bytes, cursor, 1);
    let limits = checkpoint::ReadBudget {
        bytes: budget().bytes,
        records: budget().records,
        nodes: budget().grammar_nodes,
    };
    initial.publish(&mut journal, budget().bytes, limits, 100)?;
    let initial_pin = initial.location.ok_or("initial pin absent")?;
    let old = Reader::open(&scratch.0, identity, 0, Some(initial_pin), budget())?;
    assert_eq!(old.completed_batches(), 0);
    assert!(!old.pending());
    assert!(old.families().is_empty());
    let batch = super::super::Batch::prepare(
        initial.cursor.clone(),
        initial.work,
        initial.programs,
        super::super::Budget {
            programs: 2,
            nodes: 100,
            bytes: budget().bytes,
        },
    )?;
    let mut pending = checkpoint::Frame::pending(&initial, batch)?;
    old.with_current(|| pending.publish(&mut journal, budget().bytes, limits, 100))?;
    let newer = Reader::open(&scratch.0, identity, 0, None, budget())?;
    assert!(newer.pending());
    assert_eq!(newer.completed_batches(), 0);
    assert_eq!(newer.completed_programs(), 0);
    assert!(newer.families().is_empty());
    old.require_current()?;
    let reopened = Reader::open(&scratch.0, identity, 0, Some(initial_pin), budget())?;
    assert_eq!(reopened.checkpoint(), initial_pin);
    assert!(!reopened.pending());
    assert!(Reader::open(&scratch.0, identity, 7, Some(initial_pin), budget()).is_err());
    assert!(
        Reader::open(
            &scratch.0,
            identity,
            0,
            Some((initial_pin.0, [9; 32])),
            budget()
        )
        .is_err()
    );
    assert!(
        Reader::open(
            &scratch.0,
            identity,
            0,
            Some(initial_pin),
            Budget {
                bytes: 1,
                ..budget()
            }
        )
        .is_err()
    );
    // Corruption in a later payload must refuse a latest request without
    // invalidating an explicitly pinned earlier immutable prefix.
    let next_sequence = pending.location.ok_or("pending location absent")?.0;
    let path = fixture_checkpoint_path(&scratch.0, identity, next_sequence).join("payload");
    let mut damaged = std::fs::read(&path).map_err(display)?;
    *damaged.last_mut().ok_or("fixture payload empty")? ^= 1;
    assert!(
        newer
            .with_current(|| { std::fs::write(&path, damaged).map_err(display) })
            .is_err(),
        "pinned checkpoint generations must be checked after the whole projection"
    );
    assert!(Reader::open(&scratch.0, identity, 0, None, budget()).is_err());
    Reader::open(&scratch.0, identity, 0, Some(initial_pin), budget())?.require_current()?;
    assert!(newer.require_current().is_err());
    Ok(())
}

fn fixture_checkpoint_path(root: &Path, identity: [u8; 32], sequence: u64) -> PathBuf {
    use std::fmt::Write as _;
    let id = identity.iter().fold(String::new(), |mut out, byte| {
        let _ = write!(out, "{byte:02x}");
        out
    });
    root.join(NAMESPACE)
        .join(id)
        .join(format!("{sequence:016x}"))
}

#[test]
fn orphan_acknowledged_checkpoint_is_not_silently_removed_from_cumulative_scope()
-> Result<(), String> {
    let scratch = Scratch::new().map_err(display)?;
    let raw = current(1)?;
    let identity = hash(&raw);
    let frame = checkpoint::Frame::declaration(raw, Cursor::new(&[0, 30]).map_err(debug)?, 1);
    let mut journal = Journal::open(&scratch.0, NAMESPACE, identity)?;
    journal.publish(&frame.encode()?, budget().bytes)?;
    journal.publish(&frame.encode()?, budget().bytes)?;
    let error = Reader::open(&scratch.0, identity, 0, None, budget())
        .err()
        .ok_or("orphaned complete checkpoint accepted")?;
    assert!(error.contains("omitted acknowledged"));
    Ok(())
}

#[test]
fn cumulative_charge_refuses_overflow_and_never_returns_a_prefix() {
    let mut value = 5;
    assert!(charge(&mut value, 6, 10, "fixture").is_err());
    assert_eq!(value, 5);
    let mut value = u64::MAX;
    assert!(charge(&mut value, 1, u64::MAX, "fixture").is_err());
    assert_eq!(value, u64::MAX);
    let mut value = 5;
    assert!(charge(&mut value, 5, 10, "fixture").is_ok());
    assert_eq!(value, 10);
}

fn generated_cumulative_configuration(
    fixture: &crate::candidate_universe::boolean_candidate_v1::tests::Fixture,
) -> Result<super::super::Configuration, String> {
    let capture = crate::index_stop::tests::limits();
    Ok(super::super::Configuration {
        strict: crate::audited_range_command::StrictConfig::from_values(
            Some(fixture.root.as_os_str().to_owned()),
            Some(capture.bytes.to_string().into()),
            Some(capture.records.to_string().into()),
        )
        .map_err(display)?,
        policy: policy(),
        procedure: PopulationStatisticsProcedureV2::new(255, 49, 2)?,
        capture,
        qualification: qualification::Bounds {
            candidates: 8,
            bootstrap_work: 10_000_000,
            split_work: 10_000_000,
            memory_bytes: capture.bytes,
            bytes: capture.bytes * 4,
        },
        workers: 2,
        history_bytes: capture.bytes * 4,
        replay_nodes: 10_000_000,
        source_observation_bytes: capture.bytes * 4,
    })
}

#[test]
fn two_complete_generated_families_are_parent_bound_before_cumulative_admission()
-> Result<(), String> {
    use super::super::{Request, RungScope, execute_with};
    use crate::candidate_universe::boolean_candidate_v1::tests::Fixture;
    let fixture = Fixture::new()?;
    fixture.prepare("NIFTY")?;
    let config = generated_cumulative_configuration(&fixture)?;
    let capture = config.capture;
    let request = Request {
        root: &fixture.root,
        feed: "zerodha",
        index: "NSE-NIFTY",
        // May alone has an odd session count and no canonical CSCV layout.
        // The complete two-month training span exercises actual split work.
        training: ((2025, 5), (2025, 6)),
        later: ((2025, 7), (2025, 7)),
        rungs: RungScope::new(&["1min"])?,
        alphabet: &[0, 30],
        batch_programs: 2,
        node_allowance: 100,
        batch_allowance: 2,
        configuration: &config,
    };
    let mut last = None;
    execute_with(
        &request,
        &mut |value| {
            last = Some(value);
            Ok(())
        },
        crate::index_stop::tests::load_generated,
    )?;
    let report = last.ok_or("generated search progress absent")?;
    assert_eq!(report.completed_batches, 2);
    let limits = Budget {
        bytes: capture.bytes * 16,
        records: capture.records,
        grammar_nodes: 40_000_000,
        bootstrap_work: 20_000_000,
        split_work: 20_000_000,
    };
    let reader = Reader::open(&fixture.root, report.identity, 0, None, limits)?;
    assert_eq!(reader.declaration().version(), 2);
    assert_eq!(reader.completed_batches(), 2);
    assert_eq!(reader.completed_programs(), 4);
    assert_eq!(reader.families().len(), 2);
    let training_periods = reader
        .families()
        .first()
        .ok_or("generated family absent")?
        .reader
        .training()
        .records()
        .first()
        .ok_or("generated training setting absent")?
        .periods()
        .len();
    assert_eq!(training_periods, 42);
    assert!(crate::population_observations_v1::derive_layout(training_periods)?.split_count() > 1);
    assert_eq!(
        reader
            .families()
            .iter()
            .map(|family| family.reader.rows().len())
            .sum::<usize>(),
        8
    );
    let required = reader
        .families()
        .iter()
        .try_fold((0_u64, 0_u64), |sum, family| {
            let work = family.reader.replay_work()?;
            Ok::<_, String>((
                sum.0
                    .checked_add(work.bootstrap_work)
                    .ok_or("fixture bootstrap overflow")?,
                sum.1
                    .checked_add(work.split_work)
                    .ok_or("fixture split overflow")?,
            ))
        })?;
    assert_eq!((reader.charged_work().1, reader.charged_work().2), required);
    assert!(required.0 > 1 && required.0 < config.qualification.bootstrap_work);
    assert!(required.1 > 1 && required.1 < config.qualification.split_work);
    for (index, family) in reader.families().iter().enumerate() {
        assert_eq!(family.batch, u64::try_from(index).map_err(display)?);
        assert_eq!(family.reader.search_identity(), report.identity);
        assert_eq!(family.reader.allocation().batch(), family.batch);
        for row in family.reader.training().records() {
            assert_eq!(
                row.source_id(),
                reader
                    .declaration()
                    .source(0, false)
                    .ok_or("source absent")?
                    .identity
            );
        }
    }
    check_exact_cumulative_admission(&reader, &fixture.root, limits, required)?;
    reader.require_current()?;
    check_complete_projection_leases(&reader, &fixture.root)?;
    Ok(())
}

fn check_exact_cumulative_admission(
    reader: &Reader,
    root: &Path,
    limits: Budget,
    required: (u64, u64),
) -> Result<(), String> {
    let identity = reader.declaration().identity();
    let pin = reader.checkpoint();
    let exact = Budget {
        bootstrap_work: required.0,
        split_work: required.1,
        ..limits
    };
    let tightly_admitted = Reader::open(root, identity, 0, Some(pin), exact)?;
    assert_eq!(tightly_admitted.families().len(), 2);
    assert_eq!(
        (
            tightly_admitted.charged_work().1,
            tightly_admitted.charged_work().2
        ),
        required
    );
    assert!(
        Reader::open(
            root,
            identity,
            0,
            Some(pin),
            Budget {
                bootstrap_work: required.0 - 1,
                ..exact
            }
        )
        .is_err()
    );
    assert!(
        Reader::open(
            root,
            identity,
            0,
            Some(pin),
            Budget {
                split_work: required.1 - 1,
                ..exact
            }
        )
        .is_err()
    );
    assert!(
        Reader::open(
            root,
            identity,
            0,
            Some(pin),
            Budget {
                records: 12,
                ..limits
            }
        )
        .is_err()
    );
    Ok(())
}

fn check_complete_projection_leases(reader: &Reader, root: &Path) -> Result<(), String> {
    use crate::candidate_universe::boolean_candidate_v1::persistence;
    let mut artifacts = Vec::new();
    for family in reader.families() {
        for (namespace, observation) in [
            "index-stop-qualification-v1",
            "index-stop-candidates-v1",
            "index-stop-candidates-v1",
            "index-consistency-v1",
        ]
        .into_iter()
        .zip(family.reader.observations())
        {
            artifacts.push((namespace, observation));
        }
    }
    artifacts.extend(
        reader
            .contexts
            .iter()
            .map(|context| ("index-stop-catalog-context-v1", context.observation())),
    );
    assert_eq!(artifacts.len(), reader.families().len() * 6);
    assert_eq!(
        reader.projection_scratch_bytes(),
        Observation::projection_scratch_bytes(artifacts.len())?
    );
    let artifacts = artifacts
        .into_iter()
        .map(|(namespace, observation)| {
            let identity = observation.identity();
            let body = std::fs::read(
                root.join(namespace)
                    .join(crate::identity_hex(&identity))
                    .join("body.bin"),
            )
            .map_err(display)?;
            Ok::<_, String>((namespace, identity, observation.completion_digest(), body))
        })
        .collect::<Result<Vec<_>, String>>()?;
    let assert_publishers_excluded = || {
        for (namespace, identity, _, body) in &artifacts {
            assert!(
                persistence::prepare_in_namespace(root, namespace, *identity, body).is_err(),
                "every family and source relation must remain owned across the complete comparison: {namespace}"
            );
        }
    };
    reader.with_current(|| {
        assert_publishers_excluded();
        assert!(reader.require_current().is_err());
        assert!(reader.with_current(|| Ok(())).is_err());
        let mut ranks = Vec::new();
        for family in reader.families() {
            for (setting, later) in family.reader.later().records().iter().enumerate() {
                ranks.push((later.metrics().pessimistic_paisa, family.batch, setting));
            }
            assert_publishers_excluded();
        }
        ranks.sort_unstable_by(|left, right| {
            right
                .0
                .cmp(&left.0)
                .then_with(|| left.1.cmp(&right.1))
                .then_with(|| left.2.cmp(&right.2))
        });
        assert_eq!(ranks.len(), 8);
        assert_eq!(ranks.iter().take(3).count(), 3);
        assert_publishers_excluded();
        Ok(())
    })?;
    assert_eq!(
        reader.with_current(|| {
            assert_publishers_excluded();
            Err::<(), _>("global page callback refused".to_owned())
        }),
        Err("global page callback refused".to_owned())
    );
    for (namespace, identity, pin, body) in &artifacts {
        let pending = persistence::prepare_in_namespace(root, namespace, *identity, body)?;
        assert_eq!(
            pending.finish(*identity, hash(body), body.len() as u64)?,
            *pin
        );
    }
    reader.require_current()?;
    Ok(())
}
